version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - SECRET_KEY=supersecretORISIT
    volumes:
      - ./database:/app/database
    command: python app.py
    ports:
      - "5001:5001"